<a href="https://colab.research.google.com/github/jawadAlishafaqat/House-price-prediction-california/blob/main/linear_Regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SyntaxError: invalid character '→' (U+2192) (3546989898.py, line 1)

SyntaxError: invalid character '→' (U+2192) (3006044274.py, line 1)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("/content/housing.csv")

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [5]:
df.shape

(20640, 10)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [11]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.dropna(inplace=True)

In [16]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [17]:
df["rooms_per_household"] = df["total_rooms"] / df["households"]

In [18]:
df["bedrooms_per_room"] = df["total_bedrooms"] / df["total_rooms"]

In [19]:
df["population_per_household"] = df["population"] / df["households"]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20433 entries, 0 to 20639
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   longitude                 20433 non-null  float64
 1   latitude                  20433 non-null  float64
 2   housing_median_age        20433 non-null  float64
 3   total_rooms               20433 non-null  float64
 4   total_bedrooms            20433 non-null  float64
 5   population                20433 non-null  float64
 6   households                20433 non-null  float64
 7   median_income             20433 non-null  float64
 8   median_house_value        20433 non-null  float64
 9   ocean_proximity           20433 non-null  object
 10  rooms_per_household       20433 non-null  float64
 11  bedrooms_per_room         20433 non-null  float64
 12  population_per_household  20433 non-null  float64
dtypes: float64(12), object(1)
memory usage: 2.2+ MB

In [23]:
df = pd.get_dummies(df, drop_first=True)

In [24]:
# Correlation
df.corr()["median_house_value"].sort_values(ascending=False)

median_house_value            1.000000
median_income                 0.688355
ocean_proximity_NEAR BAY      0.160526
rooms_per_household           0.151344
ocean_proximity_NEAR OCEAN    0.140378
total_rooms                   0.133294
housing_median_age            0.106432
households                    0.064894
total_bedrooms                0.049686
ocean_proximity_ISLAND        0.023525
population_per_household     -0.023639
population                   -0.025300
longitude                    -0.045398
latitude                     -0.144638
bedrooms_per_room            -0.255880
ocean_proximity_INLAND       -0.484787
Name: median_house_value, dtype: float64

In [25]:
X = df.drop("median_house_value", axis=1)

In [26]:
y = df["median_house_value"]

In [28]:
X.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,rooms_per_household,bedrooms_per_room,population_per_household,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,6.984127,0.146591,2.555556,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,6.238137,0.155797,2.109842,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,8.288136,0.129516,2.802260,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,5.817352,0.184458,2.547945,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,6.281853,0.172096,2.181467,False,False,True,False

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
mse=cross_val_score(lin_reg,X,y, scoring="neg_mean_squared_error",cv=5)
print(mse)

[-5.19567625e+09 -5.52303698e+09 -5.65195823e+09 -5.71739786e+09
 -4.38246443e+09]

In [32]:
mean_mse=np.mean(mse)
print("MSE score per fold:",mse)
print("Average Negative MSE",mean_mse)

MSE score per fold: [-5.19567625e+09 -5.52303698e+09 -5.65195823e+09 -5.71739786e+09
 -4.38246443e+09]
Average Negative MSE -5294106750.476972

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [34]:
lin_reg.fit(X_train,y_train)

LinearRegression()

In [35]:
prediction=lin_reg.predict(X_test)

In [36]:
print(prediction)

[212233.593308   146168.34886791 203451.58295568 ... 107781.02562349
 134034.777699   159973.44957584]

In [37]:
#compared a few actual value vs predicted value
compariosn_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':prediction})
print(compariosn_df.head())

       Actual Value  Predicted Value
14416      245800.0    212233.593308
16383      137900.0    146168.348868
7731       218200.0    203451.582956
1410       220800.0    177543.877752
1335       170500.0    199126.697656

In [46]:
from sklearn import metrics

r2_score = metrics.r2_score(y_test, prediction)
print(r2_score)

mae = metrics.mean_absolute_error(y_test, prediction)
print(mae)

rmse = metrics.mean_squared_error(y_test, prediction)
print(rmse)

0.6514190003460636
49774.50536974597
4766908188.849156